Repository the-17th-fox/vehicle-information-system, pull requests merged in 2022-07, with the labels that each got.

#11 Create a solution for the system #10
  src/VehicleInformationSystem.sln
  src/Web/Program.cs
  src/Web/Properties/launchSettings.json
  src/Web/Web.csproj
  src/Web/appsettings.Development.json
  src/Web/appsettings.json
Labels: good first issue

#12 Create an authorization API #2
  src/AccountsService/AccountsService.csproj
  src/AccountsService/Program.cs
  src/AccountsService/Properties/launchSettings.json
  src/AccountsService/appsettings.Development.json
  src/AccountsService/appsettings.json
  src/VehicleInformationSystem.sln
Labels: enhancement

#13 Create models for authorization API #6
  src/AccountsService/AccountsService.csproj
  src/AccountsService/Constants/Auth/AccountsPolicies.cs
  src/AccountsService/Constants/Auth/AccountsRoles.cs
  src/AccountsService/Infrastructure/Context/AccountsServiceContext.cs
  src/AccountsService/Models/User.cs
  src/AccountsService/Program.cs
Labels: enhancement

#16 Add an endpoint for creating account #3
  src/AccountsService/AccountsService.csproj
  src/AccountsService/Constants/Auth/AccountsPolicies.cs
  src/AccountsService/Constants/Auth/AccountsRoles.cs
  src/AccountsService/Constants/Logger/AccountLoggingActions.cs
  src/AccountsService/Controllers/DefaultAccountsController.cs
  src/AccountsService/Infrastructure/Context/AccountsServiceContext.cs
  src/AccountsService/Migrations/20220705135651_init.Designer.cs
  src/AccountsService/Migrations/20220705135651_init.cs
  src/AccountsService/Migrations/AccountsServiceContextModelSnapshot.cs
  src/AccountsService/Program.cs
  src/AccountsService/Services/AccountsSvc.cs
  src/AccountsService/Services/IAccountsSvc.cs
  src/AccountsService/Utilities/LoggerHelper.cs
  src/AccountsService/Utilities/MapperProfile.cs
  src/AccountsService/ViewModels/ErrorMessages/ViewModelsErrorMessages.cs
  src/AccountsService/ViewModels/RegistrationViewModel.cs
  src/AccountsService/appsettings.json
Labels: enhancement

#17 Add global error handle middleware
  src/AccountsService/Constants/Logger/AccountLoggingActions.cs
  src/AccountsService/Constants/Logger/LoggingForms.cs
  src/AccountsService/Controllers/DefaultAccountsController.cs
  src/AccountsService/Exceptions/CustomExceptions/InvalidParamsException.cs
  src/AccountsService/Exceptions/CustomExceptions/NotFoundException.cs
  src/AccountsService/Exceptions/GlobalExceptionsHandler.cs
  src/AccountsService/Program.cs
  src/AccountsService/Services/AccountsSvc.cs
  src/AccountsService/Utilities/LoggerHelper.cs
Labels: enhancement

#19 Fix missing roles property in AccountsService DbContext
  src/AccountsService/Infrastructure/Context/AccountsServiceContext.cs
Labels: invalid

#20 Add login endpoint
  src/AccountsService/AccountsService.csproj
  src/AccountsService/Constants/Logger/LoggingForms.cs
  src/AccountsService/Controllers/DefaultAccountsController.cs
  src/AccountsService/Exceptions/CustomExceptions/UnauthorizedException.cs
  src/AccountsService/Exceptions/GlobalExceptionsHandler.cs
  src/AccountsService/Program.cs
  src/AccountsService/Services/AccountsSvc.cs
  src/AccountsService/Services/IAccountsSvc.cs
  src/AccountsService/Utilities/JwtConfigugartionModel.cs
  src/AccountsService/ViewModels/LoginViewModel.cs
  src/AccountsService/appsettings.json
Labels: enhancement

#21 Add an endpoint for deleting any account for admin
  src/AccountsService/Constants/Logger/LoggingForms.cs
  src/AccountsService/Controllers/AdminAccountsController.cs
  src/AccountsService/Services/AccountsSvc.cs
  src/AccountsService/Services/IAccountsSvc.cs
Labels: enhancement

#27 Add IsDeleted check during user login
  src/AccountsService/Services/AccountsSvc.cs
Labels: bug

#29 Add user endpoint for deleting own account and fix authorization
  src/AccountsService/Controllers/DefaultAccountsController.cs
  src/AccountsService/Program.cs
  src/AccountsService/Services/AccountsSvc.cs
Labels: bug, enhancement

#33 Create docker container for the app #22
  src/.dockerignore
  src/AccountsService/Dockerfile
  src/AccountsService/Program.cs
  src/docker-compose.yml
Labels: enhancement

#35 Added an endpoint for getting list of accounts #7
  src/AccountsService/Constants/Logger/LoggingForms.cs
  src/AccountsService/Controllers/AdminAccountsController.cs
  src/AccountsService/Services/AccountsSvc.cs
  src/AccountsService/Services/IAccountsSvc.cs
  src/AccountsService/Services/Pagination/PagedList.cs
  src/AccountsService/Utilities/MapperProfile.cs
  src/AccountsService/ViewModels/PageParametersViewModel.cs
  src/AccountsService/ViewModels/PageViewModel.cs
  src/AccountsService/ViewModels/UserViewModel.cs
Labels: enhancement

#36 Add logging to MongoDB #8
  src/AccountsService/AccountsService.csproj
  src/AccountsService/Program.cs
  src/AccountsService/appsettings.json
  src/docker-compose.yml
Labels: enhancement
